---

- name: 'Create super admin group'
  ldap_entry:
    state: present
    dn: '{{ ldap_dn_admin_group }}'
    objectClass:
      - organizationalUnit
      - top
    attributes:
      ou: '{{ ldap_admin_group }}'

- name: Configure admin user
  ldap_attrs:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcRootDN: "{{ ldap_dn_bind }}"
      olcRootPW: "{{ ldap_password }}"
