---
- name: Configure ldap.conf
  template:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf

- name: Configure base DN
  ldap_attrs:
    state: exact
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcSuffix: "{{ ldap_base_dc }}"

- name: Configure LDAP modules
  ldap_entry:
    state: present
    dn: cn=module{1},cn=config
    objectClass: olcModuleList
    attributes:
      olcModulePath: /usr/lib/ldap
      olcModuleLoad:
        - memberof
        - refint

- name: Configure LDAP memberof overlay
  ldap_entry:
    state: present
    dn: olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcMemberOf
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: memberof
      olcMemberOfDangling: ignore
      olcMemberOfRefInt: 'TRUE'
      olcMemberOfGroupOC: groupOfNames
      olcMemberOfMemberAD: member
      olcMemberOfMemberOfAD: memberOf

- name: Configure LDAP refint overlay
  ldap_entry:
    state: present
    dn: olcOverlay={1}refint,olcDatabase={1}mdb,cn=config
    objectClass:
      - olcConfig
      - olcRefintConfig
      - olcOverlayConfig
      - top
    attributes:
      olcOverlay: 'refint'
      olcRefintAttribute: memberof member manager owner
