# Common Tasks
---
- fail:
    msg: You must define organizations
  when: organizations is not defined
- fail:
    msg: You must define base domain
  when: base_domain is not defined

- include_tasks: deps.yml
- include_tasks: config.yml
- include_tasks: structure.yml
- include_tasks: admin.yml
- include_tasks: organization.yml
  with_items: '{{ organizations }}'
  loop_control:
    loop_var: organization
