---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install python-ldap requirement
      package:
        name: python3-ldap
        state: present
